using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace SensateService.SqlSetup.Migrations
{
    public partial class MigrateToIdentityColumns : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"AuditLogs\" ALTER COLUMN \"Id\" DROP DEFAULT");

	        migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "AuditLogs",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint",
                oldDefaultValueSql: "nextval('\"Id_sequence\"')")
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.DropSequence( name: "Id_sequence");

            migrationBuilder.Sql("ALTER TABLE \"AspNetRoleClaims\" ALTER COLUMN \"Id\" DROP DEFAULT");
            migrationBuilder.Sql("ALTER TABLE \"AspNetRoleClaims\" ALTER COLUMN \"Id\" SET NOT NULL");
            migrationBuilder.Sql("ALTER SEQUENCE \"AspNetRoleClaims_Id_seq\" RENAME TO \"AspNetRoleClaims_Id_old_seq\"");
            migrationBuilder.Sql("ALTER TABLE \"AspNetRoleClaims\" ALTER COLUMN \"Id\" DROP DEFAULT");
            migrationBuilder.Sql("ALTER TABLE \"AspNetRoleClaims\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY");
            migrationBuilder.Sql("DROP SEQUENCE \"AspNetRoleClaims_Id_old_seq\"");

            migrationBuilder.Sql("ALTER TABLE \"AspNetUserClaims\" ALTER COLUMN \"Id\" DROP DEFAULT");
            migrationBuilder.Sql("ALTER TABLE \"AspNetUserClaims\" ALTER COLUMN \"Id\" SET NOT NULL");
            migrationBuilder.Sql("ALTER SEQUENCE \"AspNetUserClaims_Id_seq\" RENAME TO \"AspNetUserClaims_Id_old_seq\"");
            migrationBuilder.Sql("ALTER TABLE \"AspNetUserClaims\" ALTER COLUMN \"Id\" DROP DEFAULT");
            migrationBuilder.Sql("ALTER TABLE \"AspNetUserClaims\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY");
            migrationBuilder.Sql("DROP SEQUENCE \"AspNetUserClaims_Id_old_seq\"");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateSequence(
                name: "Id_sequence");

            migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "AuditLogs",
                type: "bigint",
                nullable: false,
                defaultValueSql: "nextval('\"Id_sequence\"')",
                oldClrType: typeof(long))
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "AspNetUserClaims",
                type: "integer",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "AspNetRoleClaims",
                type: "integer",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}
