

FUNCTION( prepend_path SOURCE_FILES INC_PATH )
	FOREACH( SOURCE_FILE ${${SOURCE_FILES}} )
		SET( MODIFIED ${MODIFIED} ${INC_PATH}/${SOURCE_FILE} )
	ENDFOREACH()
	SET( ${SOURCE_FILES} ${MODIFIED} PARENT_SCOPE )
ENDFUNCTION()

