#
# Docker file for DataApi.
#
# @author Michel Megens
# @email  michel@michelmegens.net
#

FROM python:3-buster

WORKDIR /build
COPY . .
RUN pip install conan && \
 apt-get update && \
 apt-get install -y cmake build-essential && \
 mkdir compile-out && cd compile-out/ && \
 conan install --build missing .. && \
 cmake -DCMAKE_BUILD_TYPE=Debug -DCONFIG_BUILD_TESTS=True -DCMAKE_INSTALL_PREFIX=`pwd`/install ../ && \
 make -j4 && bin/map_test && bin/validator_test && bin/messageservice_test && bin/zip_test && bin/sha256_test 
